# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mkorniie <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/10/30 15:05:34 by mkorniie          #+#    #+#              #
#    Updated: 2017/10/30 20:06:47 by mkorniie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror ft_display_file.c -o ft_display_file
clean:
	rm -f *.o
fclean: clean
	rm -f ft_display_file
re: fclean all

